### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by larssn**
Hi, I'm was planing on using this in a TypeScript project, and noticed there was no definition file. So here is one.

I hope the API still looks like that. If not, I'll edit it.

### CODE REVIEW

**Comment by ashtuchkin** [comment]
Awesome, thanks! Will merge soon.

**Comment by ashtuchkin** [comment]
The API looks correct from the initial look.

**Comment by larssn** [comment]
And it seems to work just fine. Even works with Rollup.

```
import iconv from 'iconv-lite';

export class test {
   constructor() {
      let dec = iconv.decode( ... );
   }
}
```

If its ok, I might pull readme.md and include this minor typescript example. Probably elaborate on it a bit.

**Comment by ashtuchkin** [comment]
Added small mention in readme. Let me know if you had something bigger in mind.

**Pull request merged**
