### PR TITLE
Move stream support into main file, drop support for extending node primitives

### PR DESCRIPTION
**Pull request by whitehat101**
Currently the project parses `process.versions.node` to decide if Stream support should be loaded.

https://github.com/ashtuchkin/iconv-lite/blob/696be8a260a9988caba0092bb5a734a96ff9bf58/lib/index.js#L138-L145

Chrome supports streams natively, Firefox is getting close, and webpack [polyfilled](https://github.com/substack/stream-browserify) support for Firefox without any config. (My project runs in a WebExtension's background page.)

Considering that Node v0.10.0 was released on [2013-03-11](https://nodejs.org/en/blog/release/v0.10.0/), it's probably fine to leave it up to the browsers/tooling/user to ensure that the environment supports Streams.

That same code block loads the depreciated feature of extending Node.js primitives, that stopped working with Node v4 ([2015-09-08](https://nodejs.org/en/blog/release/v4.0.0/)). Maybe it's a reasonable time to remove that feature and release a v0.5.0.

### CODE REVIEW

**Comment by whitehat101** [comment]
I'll give some background. I'm using mailparser, that depends on iconv-lite, in a Webpack environment (to build a Chrome/Firefox web extension). When used directly, `iconv.decode()` worked, but mailparser returned malformed text. When I made a CLI node script, I couldn't reproduce the failure. Then I found the "buggy" code in mailparser:

https://github.com/nodemailer/mailparser/blob/v2.3.4/lib/mail-parser.js#L679-L697

Since `iconv.decodeStream` wasn't defined, it silently didn't attempt to decode the stream. Webpack correctly polyfills `require('stream')` for browsers that don't yet support streams nativly, so I made a quick and dirty monkeypatch to define those functions:

https://gist.github.com/whitehat101/cb5696d669a94b11ab156b81b6392ead

I just commented out the `module.exports` function braces and added `iconv = require('iconv-lite')`. Then mailparser started correctly decoding my data.

**Comment by popod** [comment]
Hi @ashtuchkin ! Any new about this ? Do you need something more before merging this ? Thanks in advance :)

**Comment by whitehat101** [comment]
If you're interested in keeping the code to extend node primitives, if you want to keep stream support as a separate file, or if you want to use feature detection instead of version string checking, etc, let me know. I can update the pull.

I didn't think it would be a priority, since it would be supporting very old versions or deprecated features, but I could make a node v3.x or v0.10.x compatible version if that would help.

**Comment by dehru** [comment]
I'd love to get this merged in.

**Comment by dev-dan** [comment]
Would like to see this merged or issue otherwise mitigated as well. It is not uncommon for me to have to add whitehat's pull to a project due to a library utilizing iconv and encountering this issue.

**Comment by Leonardonline** [comment]
Any news/updates ?

**Comment by XVincentX** [comment]
I also subscribe to this to track it. It would be great to have this merged and released!

**Comment by ashtuchkin** [comment]
Hey @whitehat101, thank you for this PR! It was going in the right direction, but I had to change some things to avoid bloating browser bundles by default. Hopefully this would solve your use case as well. I appreciate your efforts!

Closing this PR as it's been subsumed by commits 7b78d46e9c8949332a498da9469ce79f996450c8 and 9a440ee9c98322320c4369c6e0021622600180c2.

**Comment by ashtuchkin** [comment]
Everyone subscribed please move discussion to #204.

**Pull request closed without merging**
