### PR TITLE
Remove Buffer constructor usage in tests (#197)

### PR DESCRIPTION
**Pull request by gabrielschulhof**

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
Fixes #197.

**Comment by ashtuchkin** [comment]
Looking great, thank you! You might have to add the shimming of Buffer so that the old versions of Node can use it. Will merge as soon as the tests pass.

**Comment by gabrielschulhof** [comment]
@ashtuchkin there are two places in test/main-test.js and two in test/streams-test.js where the test checks whether a value is `instanceof Buffer`. This does not work with `safer-buffer`, because its `Buffer` is a plain object, not a constructor. I'm not sure how to fix that.

**Comment by gabrielschulhof** [comment]
@ashtuchkin I went with `something instanceof Buffer.alloc(0).constructor`.

**Comment by gabrielschulhof** [comment]
@ashtuchkin in test/extend-node-test.js I had to selectively use both `"buffer"` and `"safe-buffer"`, and I had to leave one instance as `new Buffer(...)` otherwise it wouldn't pass on old Node.js.

**Comment by ashtuchkin** [comment]
Ok I rebased this PR, did some minor updates and merged it as ef662384edbdc2a5e0682ff989688d1e3885992a  Thank you!

**Pull request closed without merging**
