### PR TITLE
travis: test on iojs

### PR DESCRIPTION
**Pull request by jonathanong**

### CODE REVIEW

**Comment by dougwilson** [comment]
This requires iconv dep to be at least 2.1.5

**Comment by jonathanong** [comment]
no idea what's going on with those errors!

**Comment by dougwilson** [comment]
Weird. You wouldn't think a patch version would cause all that mess :S

**Comment by ashtuchkin** [comment]
Looks like iconv removed support for a couple of cp encodings. I tried upgrading before, but got the same errors.

**Comment by ashtuchkin** [comment]
Note, this is fixed in 14cf0cacb84e21a6d32efdda74e7ee90006dae34 after I changed tests to skip encodings that are not supported in node-iconv in ff06d8a4a4ad9ab66aa8560c789cabc5985dcaef.

**Comment by ashtuchkin** [comment]
Added bnoordhuis/node-iconv#118 to get these encodings back.

**Pull request closed without merging**
